name: busenet
description: Busenet package is a network package built on top of Dio package. It's designed to be easily integrated into your projects and used quickly. You can perform request-based caching as you wish and assign any response model you want to your network instance in a generic way.
version: 0.1.6
homepage: 'https://github.com/yunusemrealpak/busenet'

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.0.3
  dio_cache_interceptor: ^3.4.0
  dio_cache_interceptor_hive_store: ^3.2.1
  flutter:
    sdk: flutter
  path_provider: ^2.0.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null