name: busenet
description: Busenet is a network package that uses Dio underneath. It allows easy integration and quick usage, with request-based caching and generic response model assignment.
version: 0.7.1
homepage: 'https://github.com/yunusemrealpak/busenet'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.3.1
  dio_cache_interceptor: ^3.4.0
  dio_cache_interceptor_hive_store: ^3.2.1
  flutter:
    sdk: flutter
  path_provider: ^2.0.14

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null